project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Maschine Learning Fundamentals"
            file: src/Data/Chapter_1_Challenge.Rmd
          - text: "02 Supervised ML Regression"
            file: src/Data/02_supervised_ML_regression.Rmd
          - text: "03 Automated Maschine Learning with H2O"
            file: src/Data/03_automated_maschine_learning_with_H2O.Rmd
          - text: "04 Performance Measures"
            file: src/Data/01_journal/04_performance_measures.Rmd
          - text: "05 Explaining Black-Box Models With LIME"
            file: src/Data/01_journal/05_black_box_models_lime.Rmd
          - text: "06 Deep Learning"
            file: src/Data/01_journal/06_deep_learning.Rmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto